[package]
name = "slingshot"
version = "0.1.0"
edition = "2021"

[profile.release]
lto = true

[features]
rpi3 = []
rpi4 = []

[dependencies]
tock-registers = {version = "0.7.0", features = ["register_types"], default-features = false}